dialga/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views
from schedz.views import collect_phone

urlpatterns = [
    url(r'^$', RedirectView.as_view(url=r'/sched/', permanent=True), name='index'),
    # url('^', include('django.contrib.auth.urls')),
    url(r'^sched/', include('schedz.urls', namespace="schedz")),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^phone_form/', collect_phone, name='phone_form'),
    url(r'^logout/', auth_views.logout, name='logout'),
    url(r'', include('social.apps.django_app.urls', namespace='social')),
]

schedz/urls.py
from django.conf.urls import url, include

from . import views

urlpatterns = [
    url(r'^$', views.detail, name='detail'),
    url(r'^user/(?P<id>\d+)/?$', views.user, name='user'),
    url(r'^user/(?P<id>\d+)/edit/$', views.edit_user, name='edit_user'),
    url(r'^user/(?P<id>\d+)/edit/save/$', views.edit_user_save, name='edit_user_save'),
    url(r'^(?P<schedule_slug>[\w-]+)/?$', views.detail, name='detail'),
    url(r'^(?P<schedule_slug>[\w-]+)/(?P<date>\d{4}-\d{2}-\d{2})/?$', views.detail, name='detail'),
    url(r'^(?P<schedule_slug>[\w-]+)/(?P<date>\d{4}-\d{2}-\d{2})/rsvp/$', views.rsvp, name='rsvp'),
    url(r'^.*$', views.invalid, name='invalid'),

]

schedz/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
import uuid

# Create your models here.

RECENTLY_HOURS_DELTA = datetime.timedelta(hours=6)
SLOT_DURATION = datetime.timedelta(hours=1)


class Schedule(models.Model):
    name = models.CharField(max_length=20, blank=False, null=False)
    slug = models.SlugField(unique=True)
    description = models.TextField(max_length=200, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    max_slots_allowed_in_week = models.IntegerField()
    signup_opening_time = models.CharField(max_length=14,
                                           help_text="format: 'day@time' # 0-sunday, 1-monday etc. example: 3@20:00")  #
    valid_days_list = models.CommaSeparatedIntegerField(default="0,1,2,3,4,5,6", max_length=15)
    valid_times_range = models.CharField(default="00:00-23:00", max_length=14)
    is_default = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}".format(self.name)


class GlobalMessage(models.Model):
    message = models.TextField(max_length=400, blank=False, null=False)
    posted_by = models.ForeignKey(User, limit_choices_to={'is_staff': True}, blank=False, null=False)
    modified = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    related_schedule = models.ForeignKey(Schedule)

    def __str__(self):
        return "{} | BY: {}".format(self.message, self.posted_by.email)


class SchedUser(models.Model):
    uid = models.UUIDField(default=uuid.uuid4, editable=False)
    user_relation = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=12)
    auto_schedule = models.BooleanField(default=False)

    def __str__(self):
        return "{} | {}".format(self.user_relation.email, self.phone_number)


class Slot(models.Model):
    week_start = models.DateField()
    day_of_week = models.IntegerField()
    related_schedule = models.ForeignKey(Schedule)
    slot_num = models.IntegerField()
    popularity = models.IntegerField(default=0)
    assigned_user = models.ForeignKey(User, blank=True, null=True)
    modified = models.DateTimeField(auto_now=True)
    description = models.CharField(max_length=20, blank=True, null=True)
    is_permanent = models.BooleanField(default=False)
    google_event_id = models.CharField(max_length=30, blank=True, null=True)

    def abs_start_time(self):
        return datetime.datetime.combine(self.week_start + datetime.timedelta(days=self.day_of_week),
                                         datetime.time(hour=self.slot_num))

    def abs_end_time(self):
        return datetime.datetime.combine(self.week_start + datetime.timedelta(days=self.day_of_week),
                                         datetime.time(hour=self.slot_num + 1))

    def __str__(self):
        return "{:%d.%m.%Y} {:02d}:00 @ {}".format(self.week_start + datetime.timedelta(days=self.day_of_week),
                                                   self.slot_num, self.related_schedule.name)

    def was_modified_recently(self):
        return self.modified >= timezone.now() - RECENTLY_HOURS_DELTA

schedz/views.py
import datetime

from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import transaction
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.template import RequestContext, loader

from schedz.tasks import google_calendar_mgmt
from .models import Slot, GlobalMessage, Schedule, SchedUser

DAYS = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
HRS_IN_DAY = 24
DYS_IN_WEEK = 7


#################### UTILS ####################

def get_default_schedule():
    schedules = Schedule.objects.filter(is_default=True)
    if (schedules):
        return schedules[0]
    else:
        fallback = Schedule.objects.all()
        if (fallback):
            return fallback[0]
        else:
            raise Http404("No schedules found.")


def week_start_date(d):
    return d - datetime.timedelta((d.weekday() - 6) % 7)  # them calc are for sunday


def week_total_signups(schedule, user, date):
    return Slot.objects.filter(related_schedule=schedule, week_start=date, assigned_user=user).count()


def date_from_string(d):
    return datetime.datetime.strptime(d, "%Y-%m-%d").date()


def slot_valid(hour, day):
    return (hour >= 0 and hour < HRS_IN_DAY and day >= 0 and day < DYS_IN_WEEK)


#################### VIEWS ####################

@login_required
def user(request, id, saved=False):
    user = get_object_or_404(User, id=id)
    last_slots = Slot.objects.filter(assigned_user=user).order_by('-week_start')[:10]
    return render(request, 'schedz/user.html', {'user': user, 'last_slots': last_slots, 'saved': saved})


def detail(request, schedule_slug=get_default_schedule().slug, date=datetime.datetime.now().date().isoformat(),
           saved=False):
    # get requested schedule by slug
    schedule = get_object_or_404(Schedule, slug=schedule_slug)

    try:
        adj_date = week_start_date(date_from_string(date))
    except:
        raise Http404("Invalid date requested.")

    week_slots = Slot.objects.filter(week_start=adj_date, related_schedule=schedule, is_permanent=False)
    # init array
    sched = [["" for x in range(DYS_IN_WEEK)] for x in range(HRS_IN_DAY)]

    for slot in week_slots:
        if slot.assigned_user:
            sched[slot.slot_num][slot.day_of_week] = slot  # .assigned_user

    permanent_slots = Slot.objects.filter(related_schedule=schedule, is_permanent=True)

    for slot in permanent_slots:
        sched[slot.slot_num][slot.day_of_week] = slot

    template = loader.get_template('schedz/sched.html')

    # generate dates for days view
    days_with_dates = []
    for counter, day in enumerate(DAYS):
        curr_date = adj_date + datetime.timedelta(days=counter)
        days_with_dates.append("{} ({})".format(day, curr_date.strftime("%d/%m")))

    context = RequestContext(request, {
        'week_days_name': days_with_dates,
        'schedule': schedule,
        'all_schedules': Schedule.objects.all(),
        'human_week_date': adj_date.strftime("%d/%m/%Y"),
        'week_date': adj_date.isoformat(),
        'sched': sched,
        'next_week': (adj_date + datetime.timedelta(days=DYS_IN_WEEK)).isoformat(),
        'prev_week': (adj_date - datetime.timedelta(days=DYS_IN_WEEK)).isoformat(),
        'saved': saved,
        'max_slots': schedule.max_slots_allowed_in_week,
        'announcements': GlobalMessage.objects.filter(related_schedule=schedule),
    })

    return HttpResponse(template.render(context))


@login_required
def rsvp(request, schedule_slug, date):
    schedule = get_object_or_404(Schedule, slug=schedule_slug)

    date = date_from_string(date)
    req_slots = []
    del_slots = []

    if date < week_start_date(datetime.datetime.now().date()):
        return error_view(request, "Don't modify a past week, dumbass.")

    # signup opening check
    (day, tod) = schedule.signup_opening_time.split('@')
    (hours, mins) = tod.split(':')
    signup_opening = datetime.datetime.combine(
        date - datetime.timedelta(days=DYS_IN_WEEK) + datetime.timedelta(days=int(day)),
        datetime.time(int(hours), int(mins)))
    if datetime.datetime.now() < signup_opening:
        return error_view(request, "Signup for timeslots begins: {:%d/%m/%Y at %H:%M}".format(signup_opening))

    # get/parse reqs, dels
    for (k, v) in request.POST.items():
        if k.startswith('reqslot'):
            req_slots.append(k)
        if k.startswith('delslot'):
            del_slots.append(k)
            # check'em
    if len(req_slots + del_slots) <= 0:
        return error_view(request, "Please select at least one slot.")

    # handle dels
    for del_slot in del_slots:
        (hour, day) = del_slot.split(":")[1].split(',')
        hour = int(hour)
        day = int(day)

        if not slot_valid(hour, day):
            return error_view(request, "Slot validation failed")

        with transaction.atomic():
            slot, created = Slot.objects.get_or_create(related_schedule=schedule, week_start=date, day_of_week=day,
                                                       slot_num=hour)
            if slot.assigned_user == request.user:
                slot.assigned_user = None
                slot.save()
                google_calendar_mgmt(request.user, schedule, slot, action='delete').start()  ### Thread

    # Handle reqs
    if (len(req_slots) + week_total_signups(schedule, request.user, date)) > schedule.max_slots_allowed_in_week:
        return error_view(request,
                          "Can't sign up for more than %d slots in a single week." % schedule.max_slots_allowed_in_week)

    for req_slot in req_slots:
        (hour, day) = req_slot.split(":")[1].split(',')
        hour = int(hour)
        day = int(day)

        if not slot_valid(hour, day):
            return error_view(request, "Slot validation failed")

        with transaction.atomic():
            slot, created = Slot.objects.get_or_create(related_schedule=schedule, week_start=date, day_of_week=day,
                                                       slot_num=hour)

            if slot.assigned_user:
                return error_view(request, "Slot already taken. sorry.")
            else:
                slot.assigned_user = request.user
                slot.save()
                google_calendar_mgmt(request.user, schedule, slot, action='create').start()  ### Thread

    return HttpResponse(detail(request, schedule_slug, date.isoformat(), saved=True))  # return to the detail view


def invalid(request):
    return error_view(request, "Invalid URL Requested or bad week date.")


def error_view(request, err_msg):
    return render(request, "schedz/error.html", {'error': err_msg})


class PhoneForm(forms.Form):
    phone = forms.CharField(label='phone', max_length=12, required=True, validators=[RegexValidator(
        regex='^[-\d]*$',
        message='Phone must be valid',
        code='invalid_phone')], )


def collect_phone(request):
    if request.method == 'POST':
        form = PhoneForm(request.POST)
        if form.is_valid():
            request.session['phone'] = form.cleaned_data['phone']
            request.session['partial_pipeline']['phone'] = form.cleaned_data['phone']
            return redirect(reverse('social:complete', args=("google-oauth2",)))
    else:
        form = PhoneForm()

    return render(request, "schedz/phone_form.html", {'form': form})


class UserEditForm(PhoneForm):
    auto_sched = forms.BooleanField(label='auto_sched')


@login_required
def edit_user(request, id):
    user = get_object_or_404(User, id=id)
    sched_user = get_object_or_404(SchedUser, user_relation=user)

    default_data = {'phone': sched_user.phone_number, 'auto_sched': sched_user.auto_schedule}
    form = UserEditForm(default_data)
    if user == request.user:
        return render(request, 'schedz/user_edit.html', {'user': user, 'form': form})
    else:
        return error_view(request, "Don't fool around.")


@login_required
def edit_user_save(request, id):
    auth_user = get_object_or_404(User, id=id)
    sched_user = get_object_or_404(SchedUser, user_relation=auth_user)
    form = PhoneForm(request.POST)
    if auth_user == request.user:
        if form.is_valid():
            # import pdb; pdb.set_trace()
            sched_user.phone_number = form.cleaned_data['phone']
            if 'auto_sched' in request.POST:
                sched_user.auto_schedule = True
            else:
                sched_user.auto_schedule = False
            sched_user.save()
            return HttpResponse(user(request, id, saved=True))
        else:
            return error_view(request, "Error validating the form. Please enter valid values.")
    else:
        return error_view(request, "Don't fool around.")

schedz/templates/schedz/error.html
{% extends "base.html" %}

{% block content %}


<div class="jumbotron">
	<h1>Error</h1>
	<div class="alert alert-danger" role="alert">
	
	<p>{{ error }}</p>
	</div>
</div>	

<p><a href="/">Back to main page</a></p>

{% endblock %}

schedz/templates/schedz/phone_form.html
{% extends "base.html" %}

{% block content %}
<div class="jumbotron">
<h2>Complete your information:</h2>

	<form method="post" action="{% url 'phone_form' %}">
		<div class="form-group">
		{% csrf_token %}


		  <div class="form-group">
			<p><label for="exampleInputEmail1">Phone number:</label>
			{{ form.phone }}</p>
		  </div>

		<input type="submit" class="btn btn-primary btn-lg" value="Save" />
		<!--<input type="hidden" name="next" value="{{ next }}" />-->
		</div>
	</form>
</div>
{% endblock %}

schedz/templates/schedz/sched.html
{% extends 'base.html' %}

{% block head %}
    <script>
            var IS_AUTH = {{user.is_authenticated|lower}};
            var MAX_SLOTS = {{max_slots}};
    </script>
    <script src="/static/js/sched.js"></script>
{% endblock %}	

{% block nav %}
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Other Schedules<span class="caret"></span></a> 
          <ul class="dropdown-menu">
			{% for sched in all_schedules %}
				<li><a href="{% url 'schedz:detail' sched.slug %}">{{sched.name}}</a></li>
			{% endfor %}
            <!--<li role="separator" class="divider"></li>-->
          </ul>
        </li>
	{% if not user.is_authenticated %}
	<a type="button" class="btn btn-default navbar-btn navbar-right" href="{% url 'social:begin' 'google-oauth2' %}">Login</a>
	{% else %}
		{% if announcements %}
			<li><a href="#" data-toggle="modal" data-target="#announcementsModal">Announcements <span class="badge">{{announcements|length}}</span></a></li>
	    {% endif %}
	    <a type="button" class="btn btn-default navbar-btn navbar-right" href="{% url 'logout' %}?next=/">Logout</a>
	{% endif %}
{% endblock %}	

{% block content %}
	
	<div class="modal fade"  id="errModal">
		<div class="modal-dialog modal-sm">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
					<h4 class="modal-title">Error</h4>
				</div>
				<div class="modal-body">
					Please select no more than {{max_slots}} slots in a single week.
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				</div>
			</div>
		</div>
	</div>

	{% if user.is_authenticated and announcements %}
	<div class="modal fade" id="announcementsModal" tabindex="-1" role="dialog" aria-labelledby="announcementsModal">
	  <div class="modal-dialog" role="document">
		<div class="modal-content">
		  <div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			<h4 class="modal-title" id="announcementsModal">Announcements</h4>
		  </div>
		  <div class="modal-body">
			{% for announcement in announcements %}
			  <div class="entry">
				<div class="message">{{ announcement.message }}</div>
				<div class="postedBy">Posted by: <a href="{% url 'schedz:user' announcement.posted_by.id %}">
					{{ announcement.posted_by.first_name }} {{ announcement.posted_by.last_name }}</a>
				</div>
			  </div>
			{% endfor %}
		  </div>
		  <div class="modal-footer">
			<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
		  </div>
		</div>
	  </div>
	</div>
	{% endif %}

	<h2><b>{{schedule.name}}</b> schedule for the week of {{human_week_date}}</h2>
	
	{% if not user.is_authenticated %}
	<p>Please <a href="{% url 'social:begin' 'google-oauth2' %}">login using Google</a> (BGU Mail) to apply for time slots.</p>
	{% else %}
	<p>Logged in as: <a href="{% url 'schedz:user' user.id %}">{{ user.first_name }} {{ user.last_name }}</a>, {{ user.email }}</p>
	{% endif %}
	
	 <nav>
	  <ul class="pager">
		<li class="previous"><a href="{% url 'schedz:detail' schedule.slug prev_week %}"><span aria-hidden="true">&larr;</span> Previous week</a></li>
		<li class="next"><a href="{% url 'schedz:detail' schedule.slug next_week %}">Next week <span aria-hidden="true">&rarr;</span></a></li>
	  </ul>
	</nav>
	
	{% if saved %}
	<div class="alert alert-success" role="alert">Changes saved.
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
	{% endif %}
	
	<form action="{% url 'schedz:rsvp' schedule.slug week_date %}" method="post">
	{% csrf_token %}
	
    <table class="table table-bordered">
		<tr>
			<th>\</th>
		{% for day in week_days_name %}
			<th>{{day }}</th>
		{% endfor %}
		</tr>
	{% for row in sched %}
		<tr>
			<th>{{forloop.counter|add:"-1"|stringformat:"02d:00"}}</th>
		{% for slot in row %}
            {% with curr_row=forloop.parentloop.counter|add:"-1" curr_column=forloop.counter|add:"-1" %}
			    {% if slot.is_permanent %}
				    <td class="permanent" id="{{curr_row}},{{curr_column}}">
					    <p>{{ slot.description }}</p>
				    </td>
			    {% elif slot.assigned_user %}
				    <td class="assigned{% if user == slot.assigned_user %}{{" tome"}}{% endif %}" id="{{curr_row}},{{curr_column}}">
				      <p>
					    {% if user.is_authenticated %}
                          <a href="{% url 'schedz:user' slot.assigned_user.id %}">
                        {% endif %}
                          {{ slot.assigned_user.first_name }} {{ slot.assigned_user.last_name }}</a>
				      </p>
						{% if user == slot.assigned_user %}
						    <label id="{{curr_row}},{{curr_column}}">
						        <input type="checkbox" name="delslot:{{curr_row}},{{curr_column}}" id="{{curr_row}},{{curr_column}}" value="True">
                                    <span class="glyphicon glyphicon-remove" aria-hidden="true"></span>
						    </label>
						{% endif %}
				    </td>
			    {% else %} <!-- available slot -->
					{% if user.is_authenticated %}
						<td class="available"  id="{{curr_row}},{{curr_column}}">
							<label id="{{curr_row}},{{curr_column}}">
							  <input type="checkbox" name="reqslot:{{curr_row}},{{curr_column}}" id="{{curr_row}},{{curr_column}}" value="True">
								<span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
							</label>
						</td>
					{% else %}
						<td>
						</td>
					{% endif %}
			    {% endif %}
            {% endwith %}
		{% endfor %}
		</tr>
	{% endfor %}	
    </table>
	
	<div class="container">
	{% if user.is_authenticated %}
	<input type="submit" class="btn btn-primary btn-lg" value="Save Changes" />
	{% endif %}
	</div>
	
	</form>
	


	
{% endblock %}	

schedz/templates/schedz/user.html
{% extends 'base.html' %}

{% block content %}

{% if saved %}
<div class="alert alert-success" role="alert">Changes saved.
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
{% endif %}

<div class="jumbotron">
	<h1>{{ user.first_name }} {{ user.last_name }}</h1>
	
	<!--<p>Name: {{ user.first_name }} {{ user.last_name }}</p>-->

	<p>Phone: {{user.scheduser.phone_number}}</p>
	<p>Email: <a href="mailto:{{user.email}}">{{user.email}}</a></p>
	
	{% if user == request.user %}
	<p>Schedule Google Calendar events (experimental): {% if user.scheduser.auto_schedule %}Yes{% else %}No{% endif %}</p>

	<p>
		<a class="btn btn-default" href="{% url 'schedz:edit_user' user.id %}" role="button">Edit Profile</a>
	</p>
	
	<br/>
	{% endif %}
	
	<p class="lastSlots">
		<p>Latest slots:</p>
		{% if last_slots %}
			{% for slot in last_slots %}
				<li>{{ slot }}</li>
			{% endfor %}
		{% else %}
			<p>None.</p>
		{% endif %}
	</p>
	

</div>

<p><a href="/">Back to main page</a></p>
	
{% endblock %}	

schedz/templates/schedz/user_edit.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
	<h1>{{ user.first_name }} {{ user.last_name }}</h1>

	<br/>
	
	{{ form.non_field_errors }}
	{{ form.phone.errors }}
	
	<form class="form-horizontal" action="{% url 'schedz:edit_user_save' user.id %}" method="post">
	{% csrf_token %}
	  <div class="form-group">
		<label class="col-sm-2 control-label">Email</label>
		<div class="col-sm-10">
		  <p class="form-control-static">{{user.email}}</p>
		</div>
	  </div>
	  
	  <div class="form-group">
		<label for="inputPhone" class="col-sm-2 control-label">Phone</label>
		<div class="col-sm-10">
			{{ form.phone }}
		  <!--<input type="phone" class="form-control" id="phone" value="{{user.scheduser.phone_number}}">-->
		</div>
	  </div>
	  
	  <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
		  <div class="checkbox">
			<label>
				{{ form.auto_sched }}
			  Automatically Schedule Google Calendar events (experimental)
			</label>
		  </div>
		</div>
	  </div>
	  <div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
		  <button type="submit" class="btn btn-default">Save Changes</button>
		</div>
	  </div>
	</form>
</div>

<p><a href="/">Back to main page</a></p>
	
{% endblock %}	